"""empty message

Revision ID: 92184fcc69da
Revises: c48f79ecbed0
Create Date: 2020-04-30 09:23:59.543253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92184fcc69da'
down_revision = 'c48f79ecbed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'seeking_artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_artist', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
